blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/leal32b/noderium/discussions
    about: Use GitHub Discussions for questions, ideas, and general conversations.
  - name: ðŸ“– Read the Docs
    url: https://leal32b.github.io/noderium
    about: Check our documentation before opening an issue.
